In [19]:
import pandas as pd
from sklearn import model_selection
import numpy as np
from sklearn.linear_model import LogisticRegression

In [20]:
training = pd.read_csv("train.csv")
testing = pd.read_csv("test.csv")

In [21]:
training['Ticket'].value_counts()

1601                6
347082              6
3101295             6
CA. 2343            5
S.O.C. 14879        5
                   ..
368323              1
364512              1
347466              1
STON/O2. 3101271    1
367230              1
Name: Ticket, Length: 524, dtype: int64

In [22]:
title_training = []
for i in training['Name']:
    title_training.append(i.split(',')[1].split('.')[0].strip())
title_training = np.array(title_training)
title_training[title_training == 'Master']=0
title_training[title_training == 'Miss']=1
title_training[title_training == 'Mr']=2
title_training[title_training == 'Mrs']=3
title_training[(title_training!='0')&(title_training!='1')&(title_training!='2')&(title_training!='3')]=4
title_training=np.array(title_training, dtype = 'int')
title_training

array([3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 4, 3,
       3, 2, 3, 1, 2, 2, 2, 2, 3, 2, 2, 1, 4, 2, 0, 0, 2, 2, 2, 2, 3, 1,
       2, 2, 2, 2, 3, 2, 1, 0, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 2, 3, 1, 3,
       2, 2, 2, 2, 3, 2, 2, 2, 2, 1, 1, 4, 3, 3, 3, 2, 3, 2, 1, 2, 2, 2,
       2, 2, 3, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2,
       1, 3, 2, 1, 2, 2, 2, 2, 1, 1, 3, 4, 1, 1, 1, 2, 2, 2, 2, 3, 2, 1,
       2, 2, 2, 3, 2, 2, 2, 4, 2, 3, 2, 2, 2, 2, 3, 2, 1, 1, 3, 2, 3, 1,
       3, 2, 3, 2, 1, 3, 3, 1, 2, 2, 2, 4, 2, 2, 2, 0, 2, 4, 3, 2, 4, 1,
       3, 2, 2, 2, 2, 1, 3, 2, 3, 0, 2, 1, 3, 2, 2, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 1, 4, 1, 2, 1, 2, 3, 2, 2, 0, 3, 3, 1, 2, 1, 2, 2, 0, 1, 1,
       1, 2, 3, 2, 2, 2, 3, 2, 3, 2, 2, 0, 3, 2, 2, 2, 2, 3, 2, 1, 2, 2,
       2, 3, 2, 2, 1, 3, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 3, 2, 2, 4,
       2, 2, 3, 2, 2, 2, 0, 0, 2, 3, 1, 2, 2, 0, 2, 2, 2, 3, 1, 2, 2, 1,
       1, 2, 2, 2, 1, 2, 2, 1, 3, 1, 0, 2, 2, 1, 2,

In [23]:
testing

Pclass                                               Name     Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.0   
1         1                        Leader, Dr. Alice (Farnham)  female  49.0   
2         3                            Kilgannon, Mr. Thomas J    male   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4         1                          McGough, Mr. James Robert    male  36.0   
..      ...                                                ...     ...   ...   
218       3                        Lindqvist, Mr. Eino William    male  20.0   
219       1                  Butt, Major. Archibald Willingham    male  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    male  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

In [24]:
title_testing = []
for i in testing['Name']:
    title_testing.append(i.split(',')[1].split('.')[0].strip())
title_testing = np.array(title_testing)
title_testing[title_testing == 'Master'] = 0
title_testing[title_testing == 'Miss'] = 1
title_testing[title_testing == 'Mr'] = 2
title_testing[title_testing == 'Mrs'] = 3
title_testing[(title_testing != '0') & (title_testing != '1') & (title_testing != '2') & (title_testing != '3')]=4
title_testing = np.array(title_testing, dtype='int')
title_testing

array([0, 4, 2, 3, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 0, 2, 1, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 1, 2, 4, 2,
       1, 0, 2, 1, 2, 2, 2, 1, 3, 1, 2, 2, 0, 2, 2, 2, 2, 4, 3, 1, 3, 2,
       2, 4, 1, 4, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 0, 1, 1, 2, 1, 0, 1, 1, 4, 4, 2, 2,
       2, 3, 3, 2, 3, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 3, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 0, 2, 1, 3, 1, 1, 2, 2, 2, 3, 1, 3, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 2, 2, 0, 1, 3, 2, 3, 2, 1, 2, 2, 2, 3, 2, 2, 1, 1, 1,
       3, 4, 2, 4, 2, 2, 2, 2, 2, 2, 3, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 4,
       3, 2, 2])

In [35]:
tr = training 
tr = tr.drop('Name', axis=1)
tr.loc[tr['Sex'] == 'female', 'Sex']=0
tr.loc[tr['Sex'] == 'male', 'Sex'] = 1
tr.loc[tr['Age'].isnull(), 'Age']=tr.loc[tr['Age'].notnull(), 'Age'].median()
tr.loc[tr['Embarked'].isnull(), 'Embarked']='S'
tr.loc[tr['Embarked'] == 'S', 'Embarked'] = 1
tr.loc[tr['Embarked'] == 'C', 'Embarked'] = 2
tr.loc[tr['Embarked'] == 'Q', 'Embarked'] = 3
tr.loc[tr['Cabin'].isnull(), 'Cabin'] = 0
tr.loc[tr['Cabin'] != 0, 'Cabin'] = 1
tr = tr.drop('Ticket', axis = 1)
training_data = tr.values
x = training_data[:, :-1]
y = training_data[:, -1]
x = x.astype('int')
y = y.astype('int')
x = np.append(x, title_training.reshape(-1, 1), axis=1)
x.shape

(668, 9)

In [36]:
ts = testing
ts = ts.drop('Name', axis=1)
ts.loc[ts['Sex'] == 'female', 'Sex'] = 0
ts.loc[ts['Sex'] == 'male', 'Sex'] = 1
ts.loc[ts['Age'].isnull(), 'Age'] = ts.loc[ts['Age'].notnull(), 'Age'].median()
ts.loc[ts['Embarked'].isnull(), 'Embarked'] = 'S'
ts.loc[ts['Embarked'] == 'S', 'Embarked'] = 1
ts.loc[ts['Embarked'] == 'C', 'Embarked'] = 2
ts.loc[ts['Embarked'] == 'Q', 'Embarked'] = 3
ts.loc[ts['Cabin'].isnull(), 'Cabin'] = 0
ts.loc[ts['Cabin']!=0, 'Cabin'] = 1
ts = ts.drop('Ticket', axis = 1)
testing_data = ts.values
testing_data = np.append(testing_data, title_testing.reshape(-1, 1), axis = 1)
testing_data.shape


(223, 9)

In [37]:
testing_data

array([[2, 1, 8.0, ..., 0, 1, 0],
       [1, 0, 49.0, ..., 1, 1, 4],
       [3, 1, 27.0, ..., 0, 3, 2],
       ...,
       [1, 0, 17.0, ..., 1, 2, 3],
       [3, 1, 43.0, ..., 0, 1, 2],
       [2, 1, 36.5, ..., 1, 1, 2]], dtype=object)

In [38]:
training_data

array([[2, 0, 29.0, ..., 0, 1, 1],
       [3, 1, 29.0, ..., 0, 1, 0],
       [2, 1, 39.0, ..., 0, 1, 0],
       ...,
       [3, 1, 32.0, ..., 0, 1, 1],
       [3, 0, 22.0, ..., 0, 1, 0],
       [3, 0, 29.0, ..., 0, 3, 1]], dtype=object)

In [39]:
clf = LogisticRegression(solver = 'saga', max_iter = 100000, tol = 0.00001)
clf.fit(x, y)

LogisticRegression(max_iter=100000, solver='saga', tol=1e-05)

In [40]:
predicted = clf.predict(testing_data)

In [41]:
np.savetxt(X=predicted, delimiter=',', fname = 'titanic predicted.csv', fmt = '%.0f')