# Numpy 2D Array

In [1]:
import numpy as np
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Numpy's 0s and 1s

In [2]:
a = np.zeros(10, dtype = int)
a[4] = 1
for i in a:
    print(i, end = " ")

0 0 0 0 1 0 0 0 0 0 

# Numpy Inclusive

In [3]:
np.arange(9,49)


array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48])

# Identity matrix

In [4]:
identity_matrix = np.eye(5,6, dtype = int)
print(identity_matrix)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


# Cut the Rope

In [5]:
rope = np.linspace(0, 5, num=9)
for i in rope:
    j = np.round(i, 2)
    print(j)

0.0
0.62
1.25
1.88
2.5
3.12
3.75
4.38
5.0


# Print the Elements

In [6]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
for i in input_[2, 0:3]:
    print(i, end = " ")
print()
for i in input_[1:4, 3]:
    print(i, end=" ")
print()
for i in input_[2:]:
    for j in i:
        print(j, end = " ")
print()
for i in input_[1:3, 1:3]:
    for j in i:
        print(j, end =  " ")


11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

# Non - Zero elements


In [7]:
a  = np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
for i in np.where(a%3==0)[0]:
    print(i, end = ' ')

1 4 7 

# Odd elements

In [8]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
for i in a:
    if i%2 != 0:
        i = -1
    print(i, end = ' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

# Replace Max

In [9]:
a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
b = np.max(a)
for i in a:
    if i == b:
        i = 0
    print(i)

11
2
13
4
15
6
0
8
19


# Negate elements

In [10]:
a = np.arange(1,11)
a[(a>=3)*(a<=8)]*=-1
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


# Height

In [11]:
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
arr_age = age[height>155]
arr_height = height[height>155]
for i in range(len(arr_age)):
    print(arr_age[i], arr_height[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


# Sort by column

In [12]:
a = np.arange(21, 1, -1)
a.shape = (4,5)
a.sort(axis=0)
print(a)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


# Killed in USA

In [13]:
import numpy as np
import csv
file_obj = open('terrorismData.csv', encoding="UTF-8")
data = csv.DictReader(file_obj, skipinitialspace=True)

killed = []
country = []
for row in data:

    killed.append(row['Killed'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_killed[np_killed == ''] = 0.0

np_killed = np.array(np_killed, dtype='float')
np_country = np.array(country)
np_country[np_country == 'United States']
ans = np_killed[np_country == 'United States']

for i in ans:
    print(int(i))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
4
0
1
1
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0


# Total Killed in USA

In [14]:
import numpy as np
import csv
file_obj = open('terrorismData.csv', encoding="UTF-8")
data = csv.DictReader(file_obj, skipinitialspace=True)

killed = []
country = []
for row in data:

    killed.append(row['Killed'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_killed[np_killed == ''] = 0.0

np_killed = np.array(np_killed, dtype='float')
np_country = np.array(country)
np_country[np_country == 'United States']
ans = np_killed[np_country == 'United States']

print(int(np.sum(ans)))

3771


# *Assignement*

# Terror Casualty Attack

In [15]:
import numpy as np
import csv
file_obj = open('terrorismData.csv', encoding="UTF-8")
data = csv.DictReader(file_obj, skipinitialspace=True)

#List of only those columns which are to be used in output
wounded = []
killed = []
city = []
group = []
for row in data:
    if row['State'] == "Jammu and Kashmir":
        if row['Year'] == '1999':
            if row['Month'] == '5' or row['Month'] == '6' or row['Month'] == '7':
                if "Unknown" not in row['City']:
                    if "Unknown" not in row['Group']:
                        killed.append(row['Killed'])
                        wounded.append(row['Wounded'])
                        city.append(row['City'])
                        group.append(row['Group'])

# Converting to np arrays
killed = np.array(killed)
wounded = np.array(wounded)
city = np.array(city)
group = np.array(group)

#Removing null values by 0.0
killed[killed == ""] = "0.0"
wounded[wounded == ""] = "0.0"


# Convering to float from str
killed = np.array(killed, dtype=float)
wounded = np.array(wounded, dtype=float)

# calculating casuality
casualty = killed + wounded
max_casualty = (int)(casualty.max())

# get index of max casuality
max_casualty_index = casualty.argmax()
print(max_casualty, city[max_casualty_index], group[max_casualty_index])


22 Kargil District Separatists


# Terror Casualty Red

In [16]:
import numpy as np
import csv
file_obj = open('terrorismData.csv', encoding="UTF-8")
data = csv.DictReader(file_obj)

killed = []
wounded = []
for row in data:
    if row['State'] == 'Jharkhand' or row['State'] == 'Odisha' or row['State'] == 'Andhra Pradesh' or row['State'] == 'Chhattisgarh':
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])

killed = np.array(killed)
wounded = np.array(wounded)
killed[killed == ""] = "0.0"
wounded[wounded == ""] = "0.0"
killed = np.array(killed, dtype=float)
wounded = np.array(wounded, dtype=float)
casualty = np.array(killed + wounded)
print(int(sum(casualty)))

5628


# Terror City Casualty

In [22]:
import numpy as np
import csv
file_obj = open('terrorismData.csv', encoding="UTF-8")
data = csv.DictReader(file_obj)

city = []
killed = []
wounded = []
for row in data:
    if row['Country'] == 'India' and "Unknown" not in row['City']:
        city.append(row['City'])
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])


city = np.array(city)
killed = np.array(killed)
wounded = np.array(wounded)
killed[killed == ""] = "0.0"
wounded[wounded == ""] = "0.0"
killed = np.array(killed, dtype=float)
wounded = np.array(wounded, dtype=float)
casualty = np.array(killed + wounded, dtype = 'int')

citydic = {}
for i in range(len(city)):
    if city[i] in citydic:
        citydic[city[i]] += casualty[i]
    else:
        citydic[city[i]] = casualty[i]

for j in range(5):
    count = 0
    city = ''
    for i in citydic:
        if citydic[i] > count:
            count = citydic[i]
            city = i
    print(city, count)
    del citydic[city]


Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


# Terrorism FrequentDay

In [34]:
import numpy as np
import csv
file_obj = open('terrorismData.csv', encoding="UTF-8")
data = csv.DictReader(file_obj)

day = []
for row in data:
    day.append(row['Day'])

day = np.array(day, dtype = int)
day, count = np.unique(day, return_counts=True)
print(day[np.argmax(count)], count[np.argmax(count)])

15 6500
