In [41]:
import numpy as np
a = np.random.randint(1, 30, (5, 6))
print(a)

[[22  1 14 14  6 18]
 [19  6 22  9 21  4]
 [20 29 28 21 25  9]
 [29 28 23 27  7 17]
 [28 15 27  6 25 23]]


In [50]:
bool_arr = a > 20
print(bool_arr)

[[ True False False False False False]
 [False False  True False  True False]
 [False  True  True  True  True False]
 [ True  True  True  True False False]
 [ True False  True False  True  True]]


In [51]:
ans = a[bool_arr]
print(ans)

[22 22 21 29 28 21 25 29 28 23 27 28 27 25 23]


In [53]:
b = a
print(a)

[[22  1 14 14  6 18]
 [19  6 22  9 21  4]
 [20 29 28 21 25  9]
 [29 28 23 27  7 17]
 [28 15 27  6 25 23]]


In [71]:
b[bool_arr] = 100
print(b)

[[100   1  14  14   6  18]
 [ 19   6 100   9 100   4]
 [ 20 100 100 100 100   9]
 [100 100 100 100   7  17]
 [100  15 100   6 100 100]]


In [72]:
c = np.random.randint(1, 10, (2, 2))
print(c)

[[4 8]
 [7 4]]


In [74]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [83]:
#print(c[c_bool])

In [84]:
print(b)

[[100   1  14  14   6  18]
 [ 19   6 100   9 100   4]
 [ 20 100 100 100 100   9]
 [100 100 100 100   7  17]
 [100  15 100   6 100 100]]


In [85]:
bool_arr = b[:, 3] == 100
print(bool_arr)

[False False  True  True False]


In [86]:
b[bool_arr, 3] = 99
print(b)

[[100   1  14  14   6  18]
 [ 19   6 100   9 100   4]
 [ 20 100 100  99 100   9]
 [100 100 100  99   7  17]
 [100  15 100   6 100 100]]
