In [24]:
import numpy as np

li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [33]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int64
(8,)


In [35]:
print(li[3])
print(arr[3])
print(li[1:4])
print(arr[1:4])

4
4
[2, 3, 4]
[2 3 4]


In [27]:
li_2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [44]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int64
(32, 8)


In [47]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2, 1])

10
10
10


In [50]:
print(li_2d[1][:3])
print(arr_2d[1, :3])

[5, 6, 7]
[5 6 7]


In [52]:
print(li_2d[0:3][2])e

[9, 10, 11, 12]


In [71]:
ex = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [75]:
print(li_2d[0:3][0])

[1, 2, 3, 4]


In [76]:
print(arr_2d[0:3, 2])

[ 3  7 11]


In [78]:
print(arr_2d[2:4, 1:3])
print(li_2d[2:4][1:3])

[[10 11]
 [14 15]]
[[13, 14, 15, 16]]
